# Enable H2 console
spring:
  h2:
    console:
      enabled: true

  # Datasource Configuration
  datasource:
    url: jdbc:h2:mem:collections
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions} #  env variable  with default value
    api-key: ${AI_OPENAI_API_KEY}