spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1

server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans, configprops, heapdump, httpexchanges, loggers, mappings,custom-beans, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
    configprops:
      show-values: always
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1 # Only for demo purpose, change it back to 0.1 in production.

info:
  app:
    name: kays-collection-online
    description: A web application that manages collection of supernatural artifacts owned by wizards
    version: @project.version@
    author: Jeremiah Azilaku
    links:
      github: https://github.com/P-Jay-C/kays-collection-online.git