scrape_configs:
  - job_name: "kays-collection-online"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets: ["host.docker.internal:80"] # This is for demo purposes. During production, change this to the production host address.
